apiVersion: v1
kind: Service
metadata:
  name: kratos
spec:
  selector:
    app: kratos
  ports:
    - protocol: TCP
      port: 4433
      targetPort: 4433
    - protocol: TCP
      port: 4434
      targetPort: 4434

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kratos
  template:
    metadata:
      labels:
        app: kratos
    spec:
      containers:
        - name: kratos
          image: oryd/kratos:v0.8.0-alpha.3
          command: ["serve", "-c", "/etc/config/kratos/kratos.yml", "--dev", "--watch-courier"]
          env:
            - name: DSN
              value: "postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4"
          ports:
            - containerPort: 4433
            - containerPort: 4434
          volumeMounts:
            - mountPath: /etc/config/kratos
              name: kratos-config
      volumes:
        - name: kratos-config
          hostPath:
            path: /path/to/kratos
            type: Directory
