apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kratos
  template:
    metadata:
      labels:
        app: kratos
    spec:
      containers:
        - name: kratos
          image: oryd/kratos:v1.1.0
          volumeMounts:
            - name: kratos-config-volume
              mountPath: /etc/config
              subPath: ""
          command: ["kratos","serve", "-c", "/etc/config/kratos.yml", "--dev", "--watch-courier"]
          env:
            - name: DSN
              value: memory
          ports:
            - containerPort: 4433
            - containerPort: 4434
      volumes:
        - name: kratos-config-volume
          configMap:
            name: kratos-config

---
apiVersion: v1
kind: Service
metadata:
  name: kratos-admin
spec:
  selector:
    app: kratos
  ports:
    - name: admin
      protocol: TCP
      port: 4434
      targetPort: 4434
---
apiVersion: v1
kind: Service
metadata:
  name: kratos-public
spec:
  selector:
    app: kratos
  ports:
    - name: ui
      protocol: TCP
      port: 4433
      targetPort: 4433
  type: ClusterIP

