
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-selfservice-ui-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kratos-selfservice-ui-node
  template:
    metadata:
      labels:
        app: kratos-selfservice-ui-node
    spec:
      containers:
        - name: kratos-selfservice-ui-node
          image: oryd/kratos-selfservice-ui-node:v0.8.0-alpha.3
          env:
            - name: KRATOS_PUBLIC_URL
              value: "http://127.0.0.1:4433/"
            - name: KRATOS_BROWSER_URL
              value: "http://127.0.0.1:4433/"
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: kratos-selfservice-ui-node
spec:
  selector:
    app: kratos-selfservice-ui-node
  ports:
    - protocol: TCP
      port: 4455
      targetPort: 3000
